In [2]:
import numpy as np

In [3]:
def least_largest_fixed_points(P, e, pbar, tol=1e-5, verbose=False):
    """Calculate the least and the largest fixed points."""
    P, e, pbar = np.array(P), np.array(e), np.array(pbar)
    x = np.zeros(len(e))
    while 1:
        cash_flow = np.maximum(np.dot(x, P) + e, 0)
        Tx = np.minimum(cash_flow, pbar)
        if verbose:
            print(Tx)
        if np.max(np.abs(x-Tx)) < tol:
            break
        x = Tx

    print('The least fixed point:   ', Tx)

    x = pbar
    while 1:
        cash_flow = np.maximum(np.dot(x, P) + e, 0)
        Tx = np.minimum(cash_flow, pbar)
        if verbose:
            print(Tx)
        if np.max(np.abs(x-Tx)) < tol:
            break
        x = Tx

    print('The largest fixed point: ', Tx)
    return None


def Pi_matrix(n, ):
    """ a random irreducible Markov kernel, main diagonal is zero"""
    R = np.random.rand(n, n-1)
    R = R / np.sum(R, axis=1)[:, None]
    Pi = np.zeros((n, n))
    for j in range(n):
        if j == 0:
            Pi[j, 1:] = R[j,:]

        elif j == n-1:
            Pi[j, :-1] = R[j,:]
        else:
            Pi[j, 0:j] = R[j, 0:j]
            Pi[j, j+1:] = R[j, j:]
    return Pi


def e_and_Pbar(n, e1=1.5, e2=0.8,):
    """Random cash flow and liability"""
    e = np.random.rand(n) * e1 - e2
    pbar = np.random.rand(n) 
    return e, pbar

## Some cases without strong connectivity

In [707]:
P = [[0, 1, 0, 0],
     [0, 0, 1, 0],
     [0, 1, 0, 0],
     [0, 0, 1, 0]]

e = [0.1, -0.1, -3.5, 0.3]

pbar = [2, 2, 2, 2]

least_largest_fixed_points(P, e, pbar, verbose=False)

The least fixed point:    [0.1 0.  0.  0.3]
The largest fixed point:  [0.1 0.  0.  0.3]


In [708]:
P = [[0, 1, 0, 0, -1],
     [0, 0, 1, 0, -1],
     [0, 1, 0, 0, -1],
     [0, 0, 1, 0, -1],
     [0, 0, 0, 0, 0]]

e = [0.1, -0.1, -3.5, 0.3, 8]

pbar = [2, 2, 2, 2, 2]

least_largest_fixed_points(P, e, pbar, verbose=True)

[0.1 0.  0.  0.3 2. ]
[0.1 0.  0.  0.3 2. ]
The least fixed point:    [0.1 0.  0.  0.3 2. ]
[0.1 2.  0.5 0.3 0. ]
[0.1 0.5 0.  0.3 2. ]
[0.1 0.  0.  0.3 2. ]
[0.1 0.  0.  0.3 2. ]
The largest fixed point:  [0.1 0.  0.  0.3 2. ]


In [4]:
P = [[0, 1, 0, 0],
     [1, 0, 0, 0],
     [0, 0, 0, 1],
     [0, 0, 1, 0]]

e = [0.5, 0, 0.2, -0.5,]

pbar = [2, 2, 2, 2]

least_largest_fixed_points(P, e, pbar, verbose=True)

P = [[0, 1, 0, 0, -1],
     [1, 0, 0, 0, -1],
     [0, 0, 0, 1, -1],
     [0, 0, 1, 0, -1],
     [0, 0, 0, 0, 0]]

e = [0.5, 0, 0.2, -0.5, 8]

pbar = [2, 2, 2, 2, 8]

least_largest_fixed_points(P, e, pbar, verbose=True)

[0.5 0.  0.2 0. ]
[0.5 0.5 0.2 0. ]
[1.  0.5 0.2 0. ]
[1.  1.  0.2 0. ]
[1.5 1.  0.2 0. ]
[1.5 1.5 0.2 0. ]
[2.  1.5 0.2 0. ]
[2.  2.  0.2 0. ]
[2.  2.  0.2 0. ]
The least fixed point:    [2.  2.  0.2 0. ]
[2.  2.  2.  1.5]
[2.  2.  1.7 1.5]
[2.  2.  1.7 1.2]
[2.  2.  1.4 1.2]
[2.  2.  1.4 0.9]
[2.  2.  1.1 0.9]
[2.  2.  1.1 0.6]
[2.  2.  0.8 0.6]
[2.  2.  0.8 0.3]
[2.  2.  0.5 0.3]
[2.  2.  0.5 0. ]
[2.  2.  0.2 0. ]
[2.  2.  0.2 0. ]
The largest fixed point:  [2.  2.  0.2 0. ]
[0.5 0.  0.2 0.  8. ]
[0.5 0.5 0.2 0.  7.3]
[1.  0.5 0.2 0.  6.8]
[1.  1.  0.2 0.  6.3]
[1.5 1.  0.2 0.  5.8]
[1.5 1.5 0.2 0.  5.3]
[2.  1.5 0.2 0.  4.8]
[2.  2.  0.2 0.  4.3]
[2.  2.  0.2 0.  3.8]
[2.  2.  0.2 0.  3.8]
The least fixed point:    [2.  2.  0.2 0.  3.8]
[2.  2.  2.  1.5 0. ]
[2.  2.  1.7 1.5 0.5]
[2.  2.  1.7 1.2 0.8]
[2.  2.  1.4 1.2 1.1]
[2.  2.  1.4 0.9 1.4]
[2.  2.  1.1 0.9 1.7]
[2.  2.  1.1 0.6 2. ]
[2.  2.  0.8 0.6 2.3]
[2.  2.  0.8 0.3 2.6]
[2.  2.  0.5 0.3 2.9]
[2.  2.  0.5 0.  3.2]
[2.  2

In [445]:
P = [[0, 1/2, 1/2, 0, 0],
     [0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1],
     [0, 1, 0, 0, 0]]

e = [-1, 0, -0.5, 1, -0.5]

pbar = [2, 2, 0, 2, 2]

least_largest_fixed_points(P, e, pbar)

The least fixed point:    [0.  0.5 0.  1.  0.5]
The largest fixed point:  [0.  0.5 0.  1.  0.5]


In [446]:
P = [[0, 1, 0, 0, 0],
     [0, 0, 1, 0, 0],
     [0, 0, 0, 1, 0],
     [0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0]]

e = [1, 0, 0, 1, -0.5]


pbar = [2, 2, 2, 2, 2]

least_largest_fixed_points(P, e, pbar)

The least fixed point:    [1.  1.  1.  2.  1.5]
The largest fixed point:  [1.  1.  1.  2.  1.5]


In [154]:
P = [[0, 1, 0, 0, 0],
     [0, 0, 1, 0, 0],
     [0, 0, 1, 0, 0],
     [0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0]]

e = [1, -0.2, 0, 1, -0.5]


pbar = [2, 2, 0, 2, 0]

least_largest_fixed_points(P, e, pbar)

The least fixed point:    [1.  0.8 0.  1.  0. ]
The largest fixed point:  [1.  0.8 0.  1.  0. ]


In [450]:
P = [[0, 0, 0.2, 0.2, 0.5],
     [0, 0, 0.3, 0.1, 0.4],
     [0, 0, 0, 0.3, 0.1],
     [0, 0, 0, 0, 0.4],
     [0.1, 0, 0, 0, 0]]

e = [0, -0.001, 0, 0, 1]


pbar = [2, 2, 0, 2, 2]

least_largest_fixed_points(P, e, pbar, tol=1e-6)

The least fixed point:    [0.10615706 0.         0.         0.02123139 1.06157099]
The largest fixed point:  [0.10615718 0.         0.         0.02123147 1.06157133]


### Test the other operator 

In [662]:
n = 5
P = Pi_matrix(n)
pbar = np.random.rand(n) 
e = np.random.rand(n) * 1.5 - 0.5

least_largest_fixed_points(P, e, pbar)

P = np.concatenate((P, (-1) * np.ones((n, 1))), axis=1)
P = np.concatenate((P, np.zeros((1, n+1))), axis = 0)
e = np.concatenate((e, [np.sum(pbar)]))
pbar = np.concatenate((pbar, [np.sum(pbar)]))

least_largest_fixed_points(P, e, pbar)

The least fixed point:    [0.         0.         0.04944557 0.545116   0.        ]
The largest fixed point:  [0.         0.         0.04944557 0.545116   0.        ]
The least fixed point:    [0.         0.         0.04944557 0.545116   0.         1.47522928]
The largest fixed point:  [0.         0.         0.04944557 0.545116   0.         1.47522928]
